version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      cooldown:
        semver-patch: 3
        semver-minor: 3
        semver-major: 3
    labels:
      - "dependencies"
    groups:
      actions:
        patterns:
          - "*"

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      cooldown:
        semver-patch: 3
        semver-minor: 3
        semver-major: 3
    labels:
      - "dependencies"
