/**
 * Global type definitions for variables injected by Jinja2 templates
 *
 * This file provides TypeScript type information for runtime variables that are
 * injected by Python/Jinja2 into the JavaScript execution scope. These variables
 * are NOT available at compile time - they are dynamically generated by the
 * Python backend.
 *
 * Purpose:
 * - Provides IDE autocompletion and type checking in .ts fragment files
 * - Documents the contract between Python/Jinja2 (data provider) and TypeScript (consumer)
 * - Follows a "Plotly-like" specification approach where config is passed as JSON
 */

/**
 * Configuration object for SphereSource
 * Injected as: const CONFIG = {{ config | tojson }}
 */
interface SphereSourceConfig {
  /** Center point X coordinate */
  centerX: number;
  /** Center point Y coordinate */
  centerY: number;
  /** Center point Z coordinate */
  centerZ: number;
  /** Sphere radius */
  radius: number;
  /** Number of points in the azimuthal direction */
  thetaResolution: number;
  /** Number of points in the polar direction */
  phiResolution: number;
}

/**
 * Global CONFIG variable injected by Jinja2 for sphere sources
 */
declare const CONFIG: SphereSourceConfig;

/**
 * vtk.js global namespace
 * Provides access to all vtk.js modules and classes
 */
declare const vtk: any;

/**
 * Generic configuration that can be extended for other source types
 */
interface SourceConfig {
  [key: string]: any;
}
